modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"
issueTrackerURL="https://github.com/Wilyicaro/Factocrafty/issues"

[[mods]]
modId = "factocrafty"
version = "${version}"
displayName = "Factocrafty"
authors = "Wilyicaro"
displayURL="${mod_source}"
description = '''
A mod about creating and reinventing, adding machines that perform the most advanced processes, decorative blocks, power tools, 12 new ores, half of them being naturally generated, and many other usable additions.
'''
logoFile = "icon.png"

[[dependencies.factocrafty]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.factocrafty]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.factocrafty]]
modId = "factory_api"
mandatory = true
versionRange = "[2.0.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.factocrafty]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"